# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f94bc9abde49386fb4f302c953fae2eac5b359cd37d7619284b5b0abca09ae944e7f129f97af92dbeab9fa0614226c20dca416e22679d2cc7361ee6d725f8ac6

test:
  secret_key_base: 9b6dcf268d84f88ea4f18c149439460d732b680200fb24e9e7d35fd81b85d55d704275fdbccacce2a6a69bd8e6cad6a7914501495fc0f172b08a01caf071bca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
